-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:8c2fffd927964b6217842a370f248fed$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "box.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				textureRect = { x = 2, y = 180, width = 50, height = 50 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cannon01.png",
				spriteColorRect = { x = 0, y = 10, width = 102, height = 85 },
				textureRect = { x = 132, y = 93, width = 102, height = 85 },
				spriteSourceSize = { width = 128, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "cannon02.png",
				spriteColorRect = { x = 0, y = 6, width = 118, height = 89 },
				textureRect = { x = 132, y = 2, width = 118, height = 89 },
				spriteSourceSize = { width = 128, height = 95 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "cannon03.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 95 },
				textureRect = { x = 2, y = 2, width = 128, height = 95 },
				spriteSourceSize = { width = 128, height = 95 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

