-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- 
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "f1.jpg",
				spriteColorRect = { x = 0, y = 0, width = 220, height = 120 },
				textureRect = { x = 2, y = 2, width = 220, height = 120 },
				spriteSourceSize = { width = 220, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "f10.jpg",
				spriteColorRect = { x = 0, y = 0, width = 220, height = 120 },
				textureRect = { x = 2, y = 490, width = 220, height = 120 },
				spriteSourceSize = { width = 220, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "f11.jpg",
				spriteColorRect = { x = 0, y = 0, width = 220, height = 120 },
				textureRect = { x = 224, y = 490, width = 220, height = 120 },
				spriteSourceSize = { width = 220, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "f2.jpg",
				spriteColorRect = { x = 0, y = 0, width = 220, height = 120 },
				textureRect = { x = 224, y = 2, width = 220, height = 120 },
				spriteSourceSize = { width = 220, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "f3.jpg",
				spriteColorRect = { x = 0, y = 0, width = 220, height = 120 },
				textureRect = { x = 2, y = 124, width = 220, height = 120 },
				spriteSourceSize = { width = 220, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "f4.jpg",
				spriteColorRect = { x = 0, y = 0, width = 220, height = 120 },
				textureRect = { x = 224, y = 124, width = 220, height = 120 },
				spriteSourceSize = { width = 220, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "f5.jpg",
				spriteColorRect = { x = 0, y = 0, width = 220, height = 120 },
				textureRect = { x = 2, y = 246, width = 220, height = 120 },
				spriteSourceSize = { width = 220, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "f6.jpg",
				spriteColorRect = { x = 0, y = 0, width = 220, height = 120 },
				textureRect = { x = 224, y = 246, width = 220, height = 120 },
				spriteSourceSize = { width = 220, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "f7.jpg",
				spriteColorRect = { x = 0, y = 0, width = 220, height = 120 },
				textureRect = { x = 2, y = 612, width = 220, height = 120 },
				spriteSourceSize = { width = 220, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "f8.jpg",
				spriteColorRect = { x = 0, y = 0, width = 220, height = 120 },
				textureRect = { x = 2, y = 368, width = 220, height = 120 },
				spriteSourceSize = { width = 220, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "f9.jpg",
				spriteColorRect = { x = 0, y = 0, width = 220, height = 120 },
				textureRect = { x = 224, y = 368, width = 220, height = 120 },
				spriteSourceSize = { width = 220, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

