-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:d37b99cee4aa55eb2c10c62544b43ee1$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "runner.0001.png",
				spriteColorRect = { x = 79, y = 51, width = 124, height = 158 },
				textureRect = { x = 2, y = 332, width = 124, height = 158 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0002.png",
				spriteColorRect = { x = 88, y = 52, width = 86, height = 160 },
				textureRect = { x = 98, y = 2, width = 86, height = 160 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0003.png",
				spriteColorRect = { x = 79, y = 46, width = 106, height = 162 },
				textureRect = { x = 2, y = 168, width = 106, height = 162 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0004.png",
				spriteColorRect = { x = 75, y = 46, width = 132, height = 148 },
				textureRect = { x = 128, y = 322, width = 132, height = 148 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0005.png",
				spriteColorRect = { x = 64, y = 48, width = 150, height = 148 },
				textureRect = { x = 326, y = 146, width = 150, height = 148 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0006.png",
				spriteColorRect = { x = 74, y = 53, width = 138, height = 152 },
				textureRect = { x = 186, y = 2, width = 138, height = 152 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0007.png",
				spriteColorRect = { x = 78, y = 56, width = 102, height = 156 },
				textureRect = { x = 110, y = 164, width = 102, height = 156 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0008.png",
				spriteColorRect = { x = 83, y = 49, width = 94, height = 164 },
				textureRect = { x = 2, y = 2, width = 94, height = 164 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0009.png",
				spriteColorRect = { x = 86, y = 48, width = 116, height = 144 },
				textureRect = { x = 262, y = 296, width = 116, height = 144 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0010.png",
				spriteColorRect = { x = 60, y = 48, width = 154, height = 142 },
				textureRect = { x = 326, y = 2, width = 154, height = 142 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

