-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:c7363a7e0f0009f5d7b9e6ae95b26b31$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "runner.0001.png",
				spriteColorRect = { x = 88, y = 56, width = 100, height = 158 },
				textureRect = { x = 196, y = 492, width = 100, height = 158 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0002.png",
				spriteColorRect = { x = 96, y = 55, width = 88, height = 160 },
				textureRect = { x = 104, y = 168, width = 88, height = 160 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0003.png",
				spriteColorRect = { x = 93, y = 56, width = 86, height = 160 },
				textureRect = { x = 188, y = 2, width = 86, height = 160 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0004.png",
				spriteColorRect = { x = 80, y = 56, width = 94, height = 158 },
				textureRect = { x = 314, y = 162, width = 94, height = 158 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0005.png",
				spriteColorRect = { x = 75, y = 56, width = 94, height = 158 },
				textureRect = { x = 388, y = 2, width = 94, height = 158 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0006.png",
				spriteColorRect = { x = 74, y = 56, width = 90, height = 160 },
				textureRect = { x = 90, y = 336, width = 90, height = 160 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0007.png",
				spriteColorRect = { x = 75, y = 54, width = 86, height = 164 },
				textureRect = { x = 2, y = 336, width = 86, height = 164 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0008.png",
				spriteColorRect = { x = 76, y = 52, width = 92, height = 166 },
				textureRect = { x = 2, y = 2, width = 92, height = 166 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0009.png",
				spriteColorRect = { x = 75, y = 52, width = 100, height = 164 },
				textureRect = { x = 2, y = 170, width = 100, height = 164 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0010.png",
				spriteColorRect = { x = 75, y = 51, width = 106, height = 160 },
				textureRect = { x = 88, y = 502, width = 106, height = 160 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0011.png",
				spriteColorRect = { x = 76, y = 51, width = 110, height = 154 },
				textureRect = { x = 278, y = 810, width = 110, height = 154 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0012.png",
				spriteColorRect = { x = 76, y = 51, width = 114, height = 156 },
				textureRect = { x = 410, y = 162, width = 114, height = 156 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0013.png",
				spriteColorRect = { x = 75, y = 51, width = 118, height = 158 },
				textureRect = { x = 194, y = 164, width = 118, height = 158 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0014.png",
				spriteColorRect = { x = 73, y = 54, width = 120, height = 156 },
				textureRect = { x = 202, y = 652, width = 120, height = 156 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0015.png",
				spriteColorRect = { x = 74, y = 56, width = 118, height = 156 },
				textureRect = { x = 298, y = 484, width = 118, height = 156 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0016.png",
				spriteColorRect = { x = 80, y = 56, width = 110, height = 158 },
				textureRect = { x = 276, y = 2, width = 110, height = 158 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0017.png",
				spriteColorRect = { x = 89, y = 58, width = 96, height = 158 },
				textureRect = { x = 268, y = 324, width = 96, height = 158 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0018.png",
				spriteColorRect = { x = 96, y = 58, width = 84, height = 158 },
				textureRect = { x = 112, y = 824, width = 84, height = 158 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0019.png",
				spriteColorRect = { x = 96, y = 58, width = 78, height = 158 },
				textureRect = { x = 198, y = 824, width = 78, height = 158 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0020.png",
				spriteColorRect = { x = 84, y = 58, width = 84, height = 160 },
				textureRect = { x = 182, y = 330, width = 84, height = 160 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0021.png",
				spriteColorRect = { x = 76, y = 56, width = 84, height = 164 },
				textureRect = { x = 2, y = 502, width = 84, height = 164 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0022.png",
				spriteColorRect = { x = 76, y = 56, width = 90, height = 164 },
				textureRect = { x = 96, y = 2, width = 90, height = 164 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0023.png",
				spriteColorRect = { x = 79, y = 55, width = 94, height = 162 },
				textureRect = { x = 2, y = 668, width = 94, height = 162 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0024.png",
				spriteColorRect = { x = 79, y = 53, width = 102, height = 158 },
				textureRect = { x = 98, y = 664, width = 102, height = 158 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0025.png",
				spriteColorRect = { x = 78, y = 52, width = 108, height = 152 },
				textureRect = { x = 418, y = 480, width = 108, height = 152 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0026.png",
				spriteColorRect = { x = 77, y = 52, width = 114, height = 150 },
				textureRect = { x = 484, y = 320, width = 114, height = 150 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0027.png",
				spriteColorRect = { x = 77, y = 51, width = 116, height = 152 },
				textureRect = { x = 324, y = 642, width = 116, height = 152 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0028.png",
				spriteColorRect = { x = 75, y = 53, width = 118, height = 154 },
				textureRect = { x = 484, y = 2, width = 118, height = 154 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0029.png",
				spriteColorRect = { x = 76, y = 54, width = 116, height = 156 },
				textureRect = { x = 366, y = 322, width = 116, height = 156 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "runner.0030.png",
				spriteColorRect = { x = 82, y = 54, width = 108, height = 158 },
				textureRect = { x = 2, y = 832, width = 108, height = 158 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

