#!lua
local display = {}

--[[
  	Function: display.newRect
  	Creates a rectangle.
  
  	Parameters:
		x - The x coordinate of the center of the rectangle
		y - The y coordinate of the center of the rectangle
		width - The width of the rectangle
		height - The height of the rectangle

  	Returns:
		The created rectangle.
  
  	See Also:
		<rectangle>
]]
function display.newRect( x, y, width, height )
end

--[[
	Function: display.newCircle
	Create a circle.
	
	Parameters:
		x - The x coordinate of the center of the circle
		y - The y coordinate of the center of the circle
		radius - The radius of the circle

	See Also:
		<circle> 
]]
function display.newCircle( x, y, radius )
end



return display